create table TRADERESPONSE (
    USERID varchar(64),
    ITEMID varchar(50),
    COLLECTIONID varchar(64),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (ITEMID) REFERENCES ITEM(ITEMID),
    FOREIGN KEY (COLLECTIONID) REFERENCES COLLECTION(COLLECTIONID)
);