DROP TABLE USERSTATISTICS;
CREATE TABLE USERSTATISTICS (
	STATID varchar(64) PRIMARY KEY,
	USERID varchar(64) NOT NULL,
	USERLEVEL INT NOT NULL,
	MINIONSPLAYED INT NOT NULL,
	MINIONSKILLED INT NOT NULL,
	MINIONSLOST INT NOT NULL,
	HEALTHLOST INT NOT NULL,
	HEALTHTAKEN INT NOT NULL,
	TOTALWINS INT NOT NULL,
	TOTALLOSSES INT NOT NULL,
	TOTALHOURS INT NOT NULL,
	TOTALMINUTES INT NOT NULL,
	TIMESTAMP timestamp NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

CREATE TABLE CHAMPIONSTATS (
	STATID varchar(64) PRIMARY KEY,
	USERID varchar(64) NOT NULL,
	CHAMPNAME varchar(64) NOT NULL,
	MINIONSPLAYED INT NOT NULL,
	MINIONSKILLED INT NOT NULL,
	MINIONSLOST INT NOT NULL,
	HEALTHLOST INT NOT NULL,
	HEALTHTAKEN INT NOT NULL,
	TOTALWINS INT NOT NULL,
	TOTALLOSSES INT NOT NULL,
	TOTALHOURS INT NOT NULL,
	TOTALMINUTES INT NOT NULL,
	TIMESTAMP timestamp NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);