CREATE TABLE USERACHIEVES (
	STATID varchar(64) PRIMARY KEY,
	USERID varchar(64) NOT NULL,
	NAME varchar(64) NOT NULL,
	TIMESTAMP timestamp NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);




