CREATE TABLE HIGHSCORE (
   	HIGHSCOREID varchar(64) PRIMARY KEY,
    EXPERIENCE int NOT NULL,
    TIMESTAMP timestamp NOT NULL,
    USERID varchar(64) NOT NULL,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);
