create table TRADEREQUESTS (
    REQUESTID varchar(50) PRIMARY KEY,
    OFFEREDCOLLECTIONID varchar(64) not null,
    USERID varchar(64),
    FOREIGN KEY (OFFEREDCOLLECTIONID) REFERENCES COLLECTION(COLLECTIONID)
);
